# Generated by Django 5.0.6 on 2025-09-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_category_medicine_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Mobile Money', 'Mobile Money')], default='Cash', max_length=20),
        ),
    ]
