# Generated by Django 5.0.6 on 2025-09-23 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_sale_medicine_remove_sale_quantity_sold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='sale',
            name='medicine',
            field=models.ForeignKey(default=194, on_delete=django.db.models.deletion.CASCADE, to='inventory.medicine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='quantity_sold',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
    ]
