# Generated by Django 5.0.6 on 2025-09-23 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_sale_total_amount_sale_medicine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='inventory.medicine'),
        ),
    ]
