# Generated by Django 5.2.6 on 2025-09-23 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_sale_medicine_remove_sale_quantity_sold_and_more'),
        ('inventory', '0011_alter_sale_medicine'),
    ]

    operations = [
    ]
