# Generated by Django 5.2.6 on 2025-09-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_sale_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='total_medicines',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
